Added create key for admins and link to admin panel on the dashboard
DankMemer/imgen pull request #26
Opened 2018-11-14 14:32 UTC by GeoffreyWesthoff

2018-11-15 20:34 UTC, devoxin requested changes

2018-11-15 20:34 UTC, Devoxin commented on dashboard.py
> +    if user['id'] in config['admins']:
`admin = user['id'] in config['admins']`

2018-11-15 20:34 UTC, Devoxin commented on views/admin.html
> +        <h2>Active Keys</h2><a class="button" href="/createkey">Create Key</a>
new line?

2018-11-17 21:48 UTC, closed without merging

2018-11-17 21:49 UTC, GeoffreyWesthoff commented
My additions will be included in NANI's PR