New stuff
DankMemer/imgen pull request #29
Opened 2018-11-19 23:31 UTC by GeoffreyWesthoff

- pls tweet will now have data from the user instead of the big meme man
- added support for proxy servers

2018-11-20 07:48 UTC, AndyTempel requested changes

2018-11-20 07:48 UTC, AndyTempel commented on utils/http.py
> +            return Image.open(BytesIO(requests.get(config['proxy_url'] + '?url=' + url,
I think it's better to use the in-built GET parameter generator in requests. `requests.get(config['proxy_url'], params={'url': url})`

2018-11-20 07:48 UTC, AndyTempel commented on utils/http.py
> +        return requests.get(config['proxy_url'] + '?url=' + url, stream=True).content
Same here

2018-11-20 19:59 UTC, GeoffreyWesthoff commented
Good suggestion. It works fine as it is but perhaps this will help not having to deal with funky edge cases.

2018-11-22 19:59 UTC, AndyTempel requested changes

2018-11-22 19:59 UTC, AndyTempel commented on utils/http.py
> +            return Image.open(BytesIO(requests.get(config['proxy_url'],params={'url': url}, stream=True).content))
`['proxy_url'],params={'url':` lint bitte schön

2018-11-22 20:02 UTC, AndyTempel commented on utils/http.py
> +            return Image.open(BytesIO(requests.get(config['proxy_url'],params={'url': url}, stream=True).content))
@Devoxin `run_tests.py` when? :^)

2018-11-24 17:23 UTC, GeoffreyWesthoff commented on utils/http.py
> +            return Image.open(BytesIO(requests.get(config['proxy_url'],params={'url': url}, stream=True).content))
Who even cares about linting :mmlol:

2018-11-25 01:24 UTC, devoxin commented on utils/http.py
> +            return Image.open(BytesIO(requests.get(config['proxy_url'],params={'url': url}, stream=True).content))
\>:(

2018-11-25 01:25 UTC, devoxin approved these changes

2018-11-25 01:25 UTC, merged